//$("img[data-source]").size();
function LazyLoad(lazyImgs){
	var _this_=this;
	//保存所有懒加载的图片
	this.lazyImages=lazyImgs;
	//设置透明度,实现淡出效果
	this.lazyImages.css("opacity",0);
	//第一次载入页面，保存窗口大小和滚动条位置
	this.windowH=$(window).height();
	this.pageScrollTop=document.documentElement.scrollTop||document.body.scrollTop||window.pageYOffset||0;
	this.timer1=null;
	this.timer2=null;
	//浏览器窗口发生改变时
	$(window).resize(function(){
			//防止过多循环
			window.clearTimeout(_this_.timer1);
			_this_.timer1=window.setTimeout(function(){
				_this_.running();
			},200);
	});
	//滚动条事件
	$(window).scroll(function(){
			//防止过多循环
			window.clearTimeout(_this_.timer2);
			_this_.timer2=window.setTimeout(function(){
				_this_.running();
			},100);
	});
	this.init();
};
LazyLoad.prototype={
	running:function(){
		//动态改变窗口的高度
		this.windowH=$(window).height();
		this.pageScrollTop=document.documentElement.scrollTop||document.body.scrollTop||window.pageYOffset||0;
		//再次初始化
		this.init();
	},
	init:function(){
		var _this=this;
		//循环判断图片是否出现在视口中
		this.lazyImages.each(function(){
			//如果当前图片还没有加载过
			if(!$(this).data("isLoaded")){
				if($(this).offset().top<_this.windowH+_this.pageScrollTop){
					//如果出现在窗口就替换源图,如果已加载完成,循环则跳过
					$(this).attr("src",$(this).attr("data-source")).animate({opacity:1},300).data("isLoaded",true);
				};
			};
		});
	}
};
//初始化页面所有懒加载的图片
var lazyLoad=new LazyLoad($("img[data-source]"));